export const quizData = [
  {
    id: 1,
    qustion: 'Who was the first recruit of the SH crew?',
    options: ['Luffy', 'Sanji', 'Nami', 'Zoro'],
    currect: 4,
    marked: -1,
  },
  {
    id: 2,
    qustion: 'What is the clan name of Naruto',
    options: ['Uchiha', 'Uzumaki', 'Senju', 'Namikaze'],
    currect: 2,
    marked: -1,
  },
  {
    id: 3,
    qustion: "What is Tanjiro's Breathing technic",
    options: [
      'Wind Breathing',
      'Love Breathing',
      'Water Breathing',
      'Rock Breathing',
    ],
    currect: 3,
    marked: -1,
  },
  {
    id: 4,
    qustion: 'What was the Power full Eye in Naruto',
    options: ['Sharingan', 'Byakugan', 'Renigan', 'Mangekyu Sharingan'],
    currect: 3,
    marked: -1,
  },
  {
    id: 5,
    qustion: "What was the Luffy's devile fruit power",
    options: ['Hito Hito no Mi', 'Gomu Gomu', 'OP OP', 'Tori Tori'],
    currect: 1,
    marked: -1,
  },
  {
    id: 6,
    qustion: 'Who did Futaro marry? in The Quintessential Quintuplets',
    options: ['Ichika', 'Nino', 'Itsuki Nakano', 'Miku', 'Yotsuba'],
    currect: 5,
    marked: -1,
  },
  {
    id: 7,
    qustion: 'What was the First Titan of Eren Yeager',
    options: ['Founder Titan', 'Armored Titan', 'Beast Titan', 'Attack Titan'],
    currect: 4,
    marked: -1,
  },
  {
    id: 8,
    qustion: 'Who was the Hidden in the Sand, Sunagakure village Jinchuriki',
    options: ['Garra', 'Naruto', 'Son Goku', 'Matatabi'],
    currect: 1,
    marked: -1,
  },
  {
    id: 9,
    qustion: 'Who was the Upper rank 2 in Demon Slayer',
    options: ['Nakime', 'Akaza', 'Doma', 'Kokushibo', 'Gyutaro & Daki'],
    currect: 3,
    marked: -1,
  },
  {
    id: 10,
    qustion: 'Oden was the first crew member of',
    options: ['Gol.D Rojer', 'White Beard', 'Big Mom', 'Kaido'],
    currect: 2,
    marked: -1,
  },
];
